### ISSUE TITLE
onSort Callback doesn't provide the correct field. 

### ISSUE THREAD

**Issue by jnbrn** [jbetancur/react-data-table-component#113]
![image](https://user-images.githubusercontent.com/46614865/59844821-60316600-938e-11e9-8162-28e29518a1a2.png)

OnSort sends not updated state value.

**Comment by jbetancur** [comment]
This probably needs to be on componentDidUpdate. I’ll get a fix for this in today or tomorrow at the latest

**Comment by jbetancur** [comment]
The sort icon is also reversed. oops!

**Comment by jbetancur** [comment]
I will be merging a fix for this shortly as `1.6.0` since I had to change the `onSort` API slightly. In addition to returning the proper state `onSort` now returns `(column, direction, event)`.  `column` is an object containing all the fields for a column.

You can see an example of onSort here https://jbetancur.github.io/react-data-table-component/?path=/story/basic--sortable

Alternatively, you could also use `onTableUpdate` to access the table state which also has the same fields but onSort would be prefered now that it is working
