### ISSUE TITLE
Update of the entire table with search field

### ISSUE THREAD

**Issue by Angelk90** [jbetancur/react-data-table-component#128]
## Describe the bug

I have a table where I get the data from a server and the layout is done on the server side so I have a structure like this:
```
<DataTable
                  title="List user"
                  columns={columns}
                  data={data}
                  highlightOnHover
                  defaultSortField="id"
                  defaultSortAsc={false}
                  actions={actions}
                  pagination
                  paginationServer
                  paginationTotalRows={totalRows}
                  onChangeRowsPerPage={this.handlePerRowsChange}
                  onChangePage={this.handlePageChange}
                  onSort={this.handleOnSort}
                  subHeader
                  subHeaderComponent={<SubActions />}
                />
```

I put a search component in the subHeader, so that the data was searched, and every time an onChange is done on the input field it should call me a function that queries the server, takes the data and updates the table.
It works, but the problem that not only updates the data but the whole table is updated, so if I focus on the input field, that focus disappears, every time a character is typed in the input field, then the onChange function is called and then the table with the search term.

## Expected behavior
That every time the table data is updated, the whole table is not updated.

## Code Sandbox
https://codesandbox.io/s/react-data-table-sandbox-9yim4

**Comment by jbetancur** [comment]
The issue is not with the table but the fact you are nesting a component within another component render method. That is why you are re-re-rendering. Define your components on their own.

Just break the component out into its own method and pass in your value/onChange

```
const SubActions = ({ value, onChange }) => (
  <React.Fragment>
    <TextField
      fullWidth
      label="Cerca"
      placeholder={"Inserisci il termine da cercare..."}
      value={value}
      onChange={onChange}
    />
  </React.Fragment>
);
```

Then in DataTable `subHeaderComponent={<SubActions value={this.state.value} onChange={this.search} />}`

Also, you are nesting setState within setState in your change handle when you could just return a new array filtered by your array with `data.filter(....your search field)` and then `setState({ data: filteredResults })` I would recommend reading up on the React docs to make sure you understand the correct pattern 😉

**Comment by Angelk90** [comment]
@jbetancur : I did as you say but it doesn't work either.
