### ISSUE TITLE
Odd number of elements causes layout issue with paging

### ISSUE THREAD

**Issue by DocCaliban** [jbetancur/react-data-table-component#159]
## Describe the bug
When my data set has a odd number of elements, and I browse to the last page there is space added to the end for an extra blank element.

## To Reproduce
Pass in a data set with an odd number of records
Set the following props:
          pagination={true}
          paginationPerPage={10}

## Expected behavior
The scroll bar should not  be visible.
The top of the paging bar should be the same distance from the bottom of the last record as it is with an even number of records

## Code Sandbox
https://omlc7.codesandbox.io/

## Screenshots
Even Records
![image](https://user-images.githubusercontent.com/8163388/61657162-2a2a1f00-ac77-11e9-8dfd-4cf16fe34ff6.png)

Odd Records
![image](https://user-images.githubusercontent.com/8163388/61657222-4f1e9200-ac77-11e9-9eff-6fc94cecd1e9.png)

## Versions (please complete the following information)
 - React: 16.8.6
 - Styled Components: 4.3.2
 - OS: Windows 10
 - Browser Chrome, FF
 - react-data-table-component: 2.1.0

**Comment by DocCaliban** [comment]
As a side note, I notice that in my code sandbox i set the max items per page to 5, and it respects that, but then shows 10 in the UI.

Would you like another ticket for that?

**Comment by jbetancur** [comment]
hmm. I'm not able to duplicate from my chrome, safari or ff browser.  Do you have any fixed heights applied to container divs? Can you try adding a CSS normalization library like santize.css and see if that makes things better? I'm exploring the possibility that there is some CSS on the table that needs to be reset.

I've updated rdt sandbox with sanitize.css as well if you want to try recreating there, otherwise, if you can provide me a fork to your sandbox I can test as well.

https://codesandbox.io/embed/react-data-table-sandbox-ccyuu

**Comment by DocCaliban** [comment]
Ok this is really weird, I am sitting at my home pc and not seeing it, but when I point my laptop to the node instance on my hopme pc it shows the problem.  I'll do some more investigations and get back to you what I find out

**Comment by DocCaliban** [comment]
Follow up, I think but an not 100% sure this has to do with 4k.  My PC has a 4k monitor, windows uses Display Scaling to make applications readable.  So I am closing this, as I don't think it's a common scenario.
