### ISSUE TITLE
SELECT TEXT IN CELLS

### ISSUE THREAD

**Issue by hiukky** [jbetancur/react-data-table-component#187]
Do we have any options for text selection in the table? I thought about using the select property in CSS but it didn't work as expected. I looked at some previous PR but I was unsuccessful : )

**Comment by rtbishop** [comment]
If you don't have a requirement for row clicks you can set the ignoreRowClick flag to true which will allow you to select text in the cell. Code example can be found in #191

**Comment by jbetancur** [comment]
Is the use case that you need to be able to select text when ignoreRowClick is false and it is not allowing you to select? If so, this has been an issue for some time due to the way I designed ignoreRowClick (could not think of another way at the time 😞 ). Basically, if it is false I place a "masking" div on the cell to prevent clicks from propagating.

**Comment by jisi111** [comment]
sorry,I don't understand

**Comment by jbetancur** [comment]
@rtbishop is correct, what I was writing is that I need to allow you to select a cells contents when not using `column.ignoreRowClick`

**Comment by jbetancur** [comment]
In other words, you cannot currently select text contexts of a cell

**Comment by jbetancur** [comment]
#203
