### ISSUE TITLE
Table column widths should be reactive to the width of the content.

### ISSUE THREAD

**Issue by DanNeenan** [jbetancur/react-data-table-component#234]
Using datatables, I would expect the columns width to be reactive with the length of the data in the column.
In the screenshot below you can see that many of the columns have a lot of free space, but the email's are too long.
![Screenshot 2019-09-10 at 12 15 13](https://user-images.githubusercontent.com/32734342/64609469-eb862a80-d3c4-11e9-9bf9-efca49aee095.png)
This was still an issue after setting the width, minWidth or maxWidth of the columns.
And setting the column grow option to true without a width set would cause the columns to shrink to some width.
![Screenshot 2019-09-10 at 12 36 51](https://user-images.githubusercontent.com/32734342/64610664-b29b8500-d3c7-11e9-9672-cb6dc31b34c5.png)

I had tried to update the tables custom styles to `display: { some table display }` which seemed to help the column layout issue in the body, but the header would only populate the first header cell and the reactive height of the table would also be lost by doing this.
I also tried to access the tables row by assigning the DataTable component with a ref, which resulted in the error, `Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`.

I'd like to see the columns or the table have an option where we can set the table to change column width based on the table content or have that as its default setting. Another option could be to allow the cell content to break at the word level.

**Comment by jbetancur** [comment]
Instead of setting the `column.width` try using `column.grow`. RDT is based off a default flex-grow: 1 - which means it will always attempt to balance out the column size proportionally, however, you may use the `grow` column prop to allow the column to grow more (or less) by offsetting this value

It looks like you are using a custom cell component for email, which means it is up to your custom component to handle how it breaks/wraps etc... The challenge with just applying break and wrap behavior all the way down into your custom components would just pollute them with css you may not want.

I created a quick example on code sandbox to show the default behavior (default cell truncate), custom cell with grow and another custom cell with word-break: break-all applied.

https://codesandbox.io/embed/react-data-table-sandbox-custom-growwtap-9upub

Hope that helps!

**Comment by jbetancur** [comment]
I'll plan on adding a storybook for this as well to help others clarify

**Comment by DanNeenan** [comment]
Ah that example has helped a lot. I realised I was doing two things wrong. Firstly I thought grow was a bool, and secondly I was trying to set it so that all columns had the same value of grow set.
Thanks for the help!

**Comment by dandv** [comment]
I have a table with 3 narrow columns, and one wide column that should take all the remaining width.

How can the `grow` values be set so that the narrow columns are autosized to the minimum width required to accommodate the longest string, and the wide column left takes all the remaining space?

A very flexible table component I've used (Webix's [Datatable](https://webix.com/widget/datatable/)) offered a "fillspace" attribute for that long column, as seen in [this sample](https://snippet.webix.com/9208cd79).

With RDT, I tried setting `grow: 0` for the narrow columns and `grow: 1` for the wide column, but the text in the narrow columns still wraps or is cut off, and the wide column extends past the outer width of the table:

![image](https://user-images.githubusercontent.com/33569/72499326-3fd86580-3810-11ea-988f-b54955a36a01.png)

**Comment by jbetancur** [comment]
have you tried `column.width, `column. maxWidth` ` or `column.minWidth?` You can use those to fine tune cells you do not grow. Note that all cells have a default of grow: 1.

**Comment by dandv** [comment]
Yes, but with dynamic (and especially paged) data, I don't know a-priori the maximum width of a cell.

**Comment by salmanshariati** [comment]
set the `width:'auto'` solved the issue for me
