### ISSUE TITLE
selectable row checked on default on header (multi action check box)

### ISSUE THREAD

**Issue by raitalharehman** [jbetancur/react-data-table-component#271]
on header checkbox checked by default on load even none of child is checked 
![Capture](https://user-images.githubusercontent.com/24564189/66734946-6f2cae80-ee7e-11e9-866e-7799ac7f5f14.PNG)

**Comment by jbetancur** [comment]
Can you try with v3.6.1 and see if this is an issue? There were some fixes made to selectableRows that may be related.

Otherwise, I really need more information from you like a code sandbox (please use the issue template when logging an issue) or some code even. I or others can't help you with just a screenshot ;)

**Comment by raitalharehman** [comment]
thanks issue is resolved by updating.

**Comment by feiraelectronica** [comment]
> on header checkbox checked by default on load even none of child is checked
> ![Capture](https://user-images.githubusercontent.com/24564189/66734946-6f2cae80-ee7e-11e9-866e-7799ac7f5f14.PNG)

hi @raitalharehman , may i know how to do filtering like you did here? mind sharing the code here? thank you.
