### ISSUE TITLE
Can I hide a column if there is no data for that particular column?

### ISSUE THREAD

**Issue by mjacobm** [jbetancur/react-data-table-component#283]

**Comment by mjacobm** [comment]
But I need it to be visible when there are records and hidden when there are no records for that column not based on the screen size.

**Comment by jbetancur** [comment]
You could just generate your `columns` programmatically and if a field is empty in your data  just don't create that column entry in the columns array

It's an interesting request though. I'll investigate adding this as a feature.

**Comment by jbetancur** [comment]
Actually, come to think of it - this would be hard to do and would impact table performance since the onus would be on RDT to parse your data; which we do not want to do. 

Perhaps, what we can do is allow you to pass in a boolean to `column.hide`. The onus would be on you to write some logic to check your data for a consistently missing field.  something like:

```
!mydata.every(item > item.myfield`)
```

Then programmatically generate your columns based on that and for you field just pass in the result of `!mydata.every(item > item.myfield`)`

In the meantime, since `column.hide` only accepts integers,  you can use some arbitrarily high number as your hide: true condition
