### ISSUE TITLE
Post request for each row

### ISSUE THREAD

**Issue by cakerake** [jbetancur/react-data-table-component#292]
so i have a wierd situation - ill try my best to explain it properly

at first stage i load basic info to load the table let say : name only

when its loaded i want two fields in that row called todayLimit yesterdayLimit
this data is fetched by doing a post request that returns a single object

how would i do the following :

when the table loads the todaylimit and yesterdaylimit area shows a loading gif until the data is fetched and then show the new data --> and then sort the table by todaylimit (fetched data)

i can do this using state but im kind of confused how i would achieve this with the table component

any help is appreciated

**Comment by jbetancur** [comment]
Have you tried creating a custom cell using column.cell?  A custom cell is just its own component with access to the row data. in that component you could make whatever Api call you need. One thing I’d keep in mind is that might be a lot of api calls as your table grows. 

https://github.com/jbetancur/react-data-table-component#columns

**Comment by cakerake** [comment]
Yep i did think of that and it was +1 api call per row
thats why my api sends out 2 values in one call

got me scratching my head on this one

**Comment by jbetancur** [comment]
Hmmm.. why would `column.cell not work? When your custom component "mounts" it can just make the API call and set its own state to some pending status loader or whatnot.

And...  if you use pagination then let's say you allow 10 records to be displayed. That would be only 11 API calls. When you change the page and the next 10 rows load then 10 API calls are made since those custom cell components are being mounted. It's not ideal but not the worst if you are limited by the API.

Otherwise, there is no way around all the API calls unless you have access to change how the data is presented in the API you are calling.

**Comment by cakerake** [comment]
I'm trying to show 3 different values in 3 different columns

the 3 values are fetched via one single api

if i mount the same component in 3 columns then it would do 3 different calls for each row

thats the issue im trying to fix
