### ISSUE TITLE
Expansion effect of the rows

### ISSUE THREAD

**Issue by Angelk90** [jbetancur/react-data-table-component#318]
**Is your feature request related to a problem? Please describe.**

Hi @jbetancur ,
The table can be used in many ways, an interesting way in addition to the classic expandable, would be to have such an effect, see Additional context.
Where normally you see the attributes of the row for each column, but if clicked it allows the user to be able to see certain things that can only be seen through a dialog, more information.
So give more possibility to be able to personalize in the case of how much the element is clicked, in order to give a better experience.

**Additional context**

 Link: [Video](https://storage.googleapis.com/spec-host-backup/mio-components%2Fassets%2F1CKRv3HV_Dt47_p83oMTZwsbPkEFWiITR%2F04-linear-placement-attached.mp4)
![ezgif-1-87fb42b4d377](https://user-images.githubusercontent.com/20476002/69043526-83bb1400-09f3-11ea-8239-613cae888bf2.gif)

**Comment by Angelk90** [comment]
@jbetancur : 
What do you think, do you say it goes too far out of the box?

**Comment by jbetancur** [comment]
I'm not sure. I like the effect but someone else may not.  It also adds some complexity/performance hit since to animate we would have to "pre-render" the expanded row (maybe something like CSSTransition can solve this but it adds bloat).

Perhaps exposing `TableRow` as a custom component you can pass in, but it would take a lot to get there.

I'm open to PR's as long as it fits RDT's design and if you think this is something you want to solve.

**Comment by Angelk90** [comment]
@jbetancur : Is there any news?
