### ISSUE TITLE
Change row background on onRowClicked

### ISSUE THREAD

**Issue by carlosfer02** [jbetancur/react-data-table-component#334]
I have been trying to change the whole row background when i click a row, is it possible? The conditionalRowStyles option only change the rows before rendering.

**Comment by jbetancur** [comment]
Yes, this is possible!

Here you go:
https://codesandbox.io/s/react-data-table-row-select-color-example-ppbc5

I'll also add this to the storybook docs

One thing to note is I think that it's not the most performance to map through rows on every click, but I doubt it matters unless you have a hundreds of rows.

I may expose a variation to `selectableRows` where instead of a checkbox you can set a row color as selected in which case you can just access the selected row state

**Comment by jbetancur** [comment]
See related feature #326

**Comment by carlosfer02** [comment]
Awesome. thank you.

**Comment by smammadov1994** [comment]
Hey @carlosfer02 how did you get the onclick to work? I can't seem to make it happen. I want to make it so that when the expanded row is selected the row itself changes background and when it's closed it goes back to original.
