### ISSUE TITLE
Pagination buttons reversed in RTL

### ISSUE THREAD

**Issue by tomventom** [jbetancur/react-data-table-component#344]
## Describe the bug
In RTL layouts, the first page is the rightmost and paging goes from right to left.
Currently, the pagination component shifts to the left but the buttons stay in the same orientation.

## To Reproduce
Set direction='rtl' on the parent component.

## Expected behavior
Pagination component buttons should be inverted, ie first page should be the rightmost.

## Code Sandbox
https://codesandbox.io/s/react-data-table-sandbox-thokq

### Current
![Current](https://user-images.githubusercontent.com/15719371/70096328-80e53380-162f-11ea-82a6-08a03a5296a7.png)
### Expected
![Expected](https://user-images.githubusercontent.com/15719371/70096348-8fcbe600-162f-11ea-872f-066516333cb0.png)

## Versions
 - React 16.12.0
 - Styled Components 4.4.1
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Version: 78.0.3904.108

**Comment by tomventom** [comment]
Looking at the code, it seems like all that's required is removing `direction: ltr;` and flipping the svgs based on the direction, but that's way beyond my knowledge of CSS 😅

**Comment by jbetancur** [comment]
Yes! Removing that ltr css is needed, but also some css `transform: scale(-1, -1)` to flip things over when rtl is detected.  I've been fixing other rtl things internally and this issue lined up nicely with one of the things that needed to get fixed.

This will be fixed in 6.1.0 which will be released shortly.  Stay tuned!
