### ISSUE TITLE
[Feature Request] - onRowExpand, onRowCollapse events

### ISSUE THREAD

**Issue by blacksmoke26** [jbetancur/react-data-table-component#345]
Currently, I am working with the DataTable plugin.

![image](https://user-images.githubusercontent.com/425744/70262948-1959f000-17b7-11ea-8591-5f1f57e64b74.png)

I was looking for events such as `onRowExpand` and `onRowCollapse` but found nothing. I wonder if there is a way to track the state of each row?

A better way to programmatically `Expand` or `Collapse` all rows?

Any trick?

**Comment by jbetancur** [comment]
You can pre expand a row and even pre disable a row. See the Readme and storybook examples. There is no programmatic way to expand a row otherwise.

What is your use case? Why do you need a handler for row expansion?

**Comment by jbetancur** [comment]
https://jbetancur.github.io/react-data-table-component/?path=/story/expandable--default-expanded-row

Shows pre expand. Which it’s possible you can just update the state and the expanded state should change

**Comment by jbetancur** [comment]
Actually, as a 5.0 feature, I am likely removing `defaultExpandedField` and implementing something like `conditionalRowStyles`. In hindsight `defaultExpandedField` was not a great idea. Normally I would deprecate this but I am not happy with the implementation overhead and bugs I've had with it.

In short, a new prop `conditionalExpandedRows` simpy provides you will a callback to your row data so you can asset if the row should be expanded rather than hijacking your data with a `defaultExpandedField` field. 

For expander this could be just an object
new prop
conditionalExpandedRows={{
    when: row => row.expandme,
  }}

This change would also be applied to `expandableRowsDisableField` `selectableRowsPreSelectedField` and `selectableRowsDisabledField`

**Comment by blacksmoke26** [comment]
![image](https://user-images.githubusercontent.com/425744/70360980-e17ba700-18a1-11ea-86b1-2dcf8839b44c.png)

I have implemented something like:
Mark as `read` _(message)_ when expanded. But now I have no other way to detect the change of row expanded to trigger 'Mark status as Read'.

**Comment by jbetancur** [comment]
I'll be implementing this in a 5.0 version tonight. `onRowExpandToggled` will return (expandState, row) .

**Comment by jbetancur** [comment]
Release 5.0.0 is now available - please see the release notes for changes

**Comment by blacksmoke26** [comment]
Yeah sure. I am working on my app, so I will implement a new feature for sure.

**Comment by blacksmoke26** [comment]
@jbetancur I have made changes according to the latest version.

Working great. Thank you!
