### ISSUE TITLE
{data} format not clear in documentation

### ISSUE THREAD

**Issue by agitnaeta** [jbetancur/react-data-table-component#369]
## Describe the bug
Documentation doesn't clear about default **data** format, 
I really struggle ling what the data format actually, You always mention {data} without explaining what the format its array or key-value data

**Comment by jbetancur** [comment]
https://github.com/jbetancur/react-data-table-component#datatable-properties

i.e.

data | array | no | [] | it is highly recommended that your data has a unique identifier (keyField). The default keyField is id. If you need to override this value then see keyField DataTable Properties.
-- | -- | -- | -- | --



If `data` type is an array as mentioned in the README me then it is implied that it is an array of objects since you are describing columns of data.

e.g.

```js
const myData = [{ id: 1, name: 'test' }, ...];
```
