### ISSUE TITLE
React Hook useEffect has a missing dependency: 'fetchUsers'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

### ISSUE THREAD

**Issue by maithuy** [jbetancur/react-data-table-component#390]
## Describe the bug
Component with React Hooks has useEffect warning

## To Reproduce
https://jbetancur.github.io/react-data-table-component/?path=/story/pagination--server-side-using-hooks

## Expected behavior
No warning

## Versions (please complete the following information)
 - React 16.11.0
 - Styled Components
 - OS: Mac

**Comment by jbetancur** [comment]
That [] is intentional and it means only run the effect once which is exactly what is intended when loading the initial data. If you add fetchUsers to that [] or you remove [] you will get an infinite loop. The linter is meant to be a guide but it is not perfect in this use case.

The fix here should be to disable the linter warning or until the linter gets smarter about the use case. There is no bug as nothing is broken per se.

This SO answers further clarifies
https://stackoverflow.com/questions/55840294/how-to-fix-missing-dependency-warning-when-using-useeffect-react-hook

A correct example fetching in a hook - notice that defining the hook in the function does not show the warning, this is because the linter isn't "smart" enough
https://www.robinwieruch.de/react-hooks-fetch-data
