### ISSUE TITLE
How to render server side pagination?

### ISSUE THREAD

**Issue by kanji-stack-dev** [jbetancur/react-data-table-component#405]
Currently, all the records are being retrieved in one go and they are managed to display using Pagination links. I want to call one page at a time from the server when pagination link is clicked. What if the number of records is too large?
All I am looking for is server-side rendering for pagination.

**Comment by jbetancur** [comment]
Here is an RDT example using server side pagination with the github API

https://jbetancur.github.io/react-data-table-component/?path=/story/pagination--server-side

For server-side pagination you will need an API that supports pagination in the response

**Comment by kanji-stack-dev** [comment]
Is such a possibility of searching using this way? if this type demo available on your doc so please share with me..

**Comment by jbetancur** [comment]
This example shows client-side filtering which would be very similar so server-side search.  All that is happening here is that your data is being updated and RDT will re-render accordingly.  

Instead of filtering you would just have your input onChange make an API call with the search params and then update the data state accordingly.

https://jbetancur.github.io/react-data-table-component/?path=/story/filtering--example-1

**Comment by HARISMEHMOOD** [comment]
@jbetancur for server side pagination with redux, whenever I click to move to next page, the request go fine, but instead of table showing next page, it appends the rows below the current state of table. Any idea why it might be doing that ?
