### ISSUE TITLE
Cannot use `selectableRowSelected` and `onSelectedRowsChange` together

### ISSUE THREAD

**Issue by DjLeChuck** [jbetancur/react-data-table-component#420]
## Describe the bug
When using `selectableRowSelected` to have default selected checkboxes and `onSelectedRowsChange` to track selected checkboxes in a state, the change event is triggered twice, so the checkbox is checked then immediatly unchecked (and vice versa).

## To Reproduce
1. Set a data table with `selectableRowSelected` and `onSelectedRowsChange`
2. Use a state to store `selectedRows`
3. Click on a checkbox, his state will change twice, so it remain checked (or unchecked)

## Expected behavior
The change event should be fired once per click, not twice.

## Code Sandbox
[![Edit React Data Table Sandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-data-table-sandbox-u3run?fontsize=14&hidenavigation=1&theme=dark)

## Versions (please complete the following information)
 - React
 - Styled Components
 - OS: Linux
 - Browser: Chrome 79

**Comment by jbetancur** [comment]
Which version of rdt are you using?

**Comment by DjLeChuck** [comment]
The last, 6.2.0 as in the CodeSandbox! :smiley:

**Comment by jbetancur** [comment]
Heh sorry just noticed the codesandbox - thank you for that. One thing you can try is memoizing the selectable Props that you are passing in as functions. When you pass functions arrays or objects directly (because these are by reference) and your component state changes react thinks they are updated props. That might prevent the extra re-render in this case.


In any case,  I’ll have a look later today ibecause regardless that call back should only ever fire once even if rdt is re-rendering multiple times

**Comment by jbetancur** [comment]
This will workaround your issue for now. Move the selectableRowSelected out of the component so it is not re-created. 

```js
const preSelected = row => row.runtime > 100;

function App() {
  const [, setSelection] = useState({});

  return (
    <div className="App">
      <DataTable
        title="Movies"
        columns={columns}
        data={movies}
        defaultSortField="title"
        pagination
        selectableRows
        selectableRowSelected={preSelected}
        onSelectedRowsChange={state => {
          console.log("change");
          setSelection(state.selectedRows);
        }}
      />
    </div>
  );
```
