### ISSUE TITLE
Improve IDataTableColumn typing

### ISSUE THREAD

**Issue by michaeljota** [jbetancur/react-data-table-component#432]
## Describe the bug
In the examples, where `cell` property is defined, `selector` is not used. Leaving me to think maybe the right type for the IDataTableColumn is a union type, with a base type, and discrimination between the usage of `cell` and `selector`. 

Something like: 
```ts
interface IDataTableColumnCommon {
  // All properties but cell or selector.
}

interface IDataTableColumnWithSelector extends IDataTableColumnCommon {
  selector: string;
}

interface IDataTableColumnWithCell extends IDataTableColumnCommon {
  (row: T) => React.Node
}
```

However, with the current implementation, there is a compilation error from TS.

## To Reproduce
1. Create a new React App with Typescript and add React Data Table Component.
2. Try to reproduce the [Custom Cells Example](https://jbetancur.github.io/react-data-table-component/?path=/story/custom-cells--example-1)

## Expected behavior
There is an error because of how types are defined. There should be no errors.

## Code Sandbox

https://stackblitz.com/edit/react-data-table-component-typing-bug?file=BasicTable.tsx

You can see the error in line `77`.

## Versions (please complete the following information)
 - React: 16.12.0
 - Styled Components: 5.0.0
 - Version: 6.2.1

## PS:

The `selector` property typing could also be improved if it is narrowed to `keyof T` instead of `string`.

```ts
interface IDataTableColumnWithSelector<T> extends IDataTableColumnCommon<T> {
  selector: keyof T;
}
```

**Comment by jbetancur** [comment]
So, `selector` is used for displaying data when for a basic column (ie not using cell) as well as for sorting (cell does not help you with sorting). In fact,  leaving selector off will currently throw an exception, which is why I originally made it required.

However, there are cases when you don't want a selector such as a field with a button or action or, you simply do not want to sort.

I'll mark this as enhancement and actually make `selector` optional as well as a change so that RDT will set it to null to avoid the exception.  The data will not render, or be sortable in basic examples, but that's what the README and storybooks are for 😉 

Back to your issue! The workaround until I get a pathch out is just set `selector: null,` on fields you do not need to sort

If you know a better way to handle this with types I am open to PR's! Otherwise, hope this helps.
