### ISSUE TITLE
sortFunction doesn't update table ordering when on the first page of table

### ISSUE THREAD

**Issue by rjray** [jbetancur/react-data-table-component#437]
I have a table whose first column is a series of values that are more-or-less like software version numbers (they're magazine issue numbers, "1.1", "2.12", etc.). I wrote a custom sort-handler to use a function I cribbed from an ACM site to sort this column (and use typical approaches for the plain data columns).

The problem: If I click on the sort-icon while on the first page of paginated results, the table ordering doesn't update. If I use the pagination controls to go to page 2 (or any page != 1) and sort, it correctly re-orders the table. This also happens if there is only one page of results in the pagination. However, this does not happen when pagination is not enabled (it works correctly in that case).

(I don't have a ready-to-go sandbox example for this, as the data comes from a MySQL source. I can try to replicate enough to demo the problem if needed.)

**Comment by KatiaPosPago** [comment]
Same issue here.

**Comment by jbetancur** [comment]
Yea, it might be easier to do this as a code sandbox and just mock a few records of your data. 

I set one  up here with a customSort
https://codesandbox.io/s/react-data-table-sandbox-custom-sort-bug-qunnh

**Comment by rjray** [comment]
I will try to distill the issue into a sandbox this weekend.

**Comment by rjray** [comment]
I have managed to create a sandbox that demonstrates the problem: https://codesandbox.io/s/react-data-table-custom-sort-bug-sandbox-kgx3q

**Comment by jbetancur** [comment]
Thank you and sorry for the late response. This looks like a bug when using pagination. I'll tag as a bug and look at getting a fix in a release.

**Comment by rjray** [comment]
This is not a stale issue.

**Comment by rjray** [comment]
Still present in version 6.9.3.

**Comment by rjray** [comment]
Still present in 6.9.7.

**Comment by elephantNic** [comment]
Same issue here, any updates? Thanks

**Comment by jbetancur** [comment]
Ok, I finally had some time to look at this. @rjray thanks for the sandbox. It looks like everything works if you pass a new `rows` reference of rows on line 37:

`return rows.slice(0); // slice in this case returns a new array` 

The `rows` you return must be a different object because `Array.sort` does not return a new array. Instead, it sorts your array in place. In JavaScript, object/array equality is by reference and not by contents, so because sorting does not change its reference React does not know it needs to "re-render" (i.e that the data has changed).

I think what we could probably do is enhance the documentation to call this out in the README since it is not immediately obvious.

**Comment by jbetancur** [comment]
@elephantNic See comment above and see if that solves your issue.

**Comment by jbetancur** [comment]
Updated to README
https://github.com/jbetancur/react-data-table-component/commit/a06abe39cb2e916452d76660cb7d442958dfb837
