### ISSUE TITLE
Add Searching 

### ISSUE THREAD

**Issue by Intelliflex** [jbetancur/react-data-table-component#463]
## Issue Check list
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README to ensure the feature is not already present
- [x] Considered the value versus complexity for all users of the library as well as library maintenance
- [x] Considered if this can be a storybook or documentation example

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the featre is.

**Describe the solution you'd like**
I have spent the last few days converting some of my table based libraries over to react-data-table-component to simplify drill down operations. This works great - a credit to you jbetancur! When I was evaluating the product I saw the kitchen sink (storybook) example with a search facility and looked no further. It turns out searching is not currently supported? As this is a fairly easy thing to do (filtering the data object) it would be nice to see it supported in the product rather than having to do externally

Here is an example of my current drill down screen, where I would like to also allow search

![trustpointTable](https://user-images.githubusercontent.com/50093911/74817536-c66cef00-5348-11ea-8709-c51c90a2ecf9.jpg)

**Comment by jbetancur** [comment]
Hey @Intelliflex! That's a really slick use case with nesting that had not occurred to me. We must have this as a storybook example for nesting!

So as for searching, you are correct that it is just filtering the data (it could also be an API call to a search API), which is why [I made search/filter and external implementation in this storybook](https://jbetancur.github.io/react-data-table-component/?path=/story/filtering--example-1). Not sure if you saw that one (the docs could use some search themselves) but give it a try.
