### ISSUE TITLE
Datatable triggering onChangePage while sorting

### ISSUE THREAD

**Issue by diegomanansala** [jbetancur/react-data-table-component#466]
## Issue Check list
- [ ] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [ ] Read the README
- [ ] You are using React 16.8.0+
- [ ] You installed `styled-components`
- [ ] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
onChangePage callback is being called when sorting while in page 2 and beyond. onChangePage does not get triggered when sorting while in page 1.

## To Reproduce
1. Go to next page
2. Sort by title

## Expected behavior
onChangePage should not be triggered while sorting, since it interferes with the onSort callback. This especially becomes problematic when you call an API for the pagination and sorting.

## Code Sandbox, Screenshots, or Relevant Code

https://codesandbox.io/embed/react-data-table-sandbox-ccyuu

## Versions (please complete the following information)
 - React (RDT requires 16.8.0+)
 - Styled Components
 - OS: macOS 10.14.6 
 - Browser Chrome 79.0.3945.130

**Comment by jbetancur** [comment]
`onChangePage` fires by design because the behavior is when a sort occurs that the table pages back to page 1.  

However, you are correct that when using `onChangePage` and `onSort` together the pagination breaks when a sort is fired and internally the `onChangePage` follows.

I could add a fix when using the `paginationServer` (which really just means "manual" paging) to ignore going to page 1 and let the developer handle that requesting the updated sort

**Comment by jbetancur** [comment]
Ok I have a viable fix. New prop `onPaginate` which only fires on pagination that is manually performed. WIll merge this shortly into a 6.4.0

**Comment by jbetancur** [comment]
Still working on this. Not as easy as I thought to fix.

**Comment by dmushkov** [comment]
any news about this?

**Comment by matijagalina** [comment]
It can be "fixed" by making custom Pagination component which will handle pagination manually. Just add pagination={false} as a prop to the DataTable and use your own pagination component. I did that since I had to use server side sorting and pagination.
Custom pagination component is pretty much the same as this one - https://github.com/jbetancur/react-data-table-component/blob/master/src/DataTable/Pagination.js
