### ISSUE TITLE
Striped flag doesn't seem to be working

### ISSUE THREAD

**Issue by ospfranco** [jbetancur/react-data-table-component#540]
## Issue Check list
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README
- [x] You are using React 16.8.0+
- [x] You installed `styled-components`
- [x] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
I'm trying to display striped rows, however the flag doesn't seem to be doing anything by default, I also tried to add a custom theme and again no styling is applied

## To Reproduce
1. Use the `striped` flag

## Expected behavior
Odd row are properly colored, even without an explicit theme

## Code Sandbox, Screenshots, or Relevant Code
https://codesandbox.io/embed/vigorous-darwin-zbbfo

## Versions (please complete the following information)
 - React 16.12.0
 - Styled Components 5.0.1
 - OS: Web
 - Browser: Safari/Firefox

**Comment by jbetancur** [comment]
So that is really odd. I tried the dupe this across chrome safari and firefox and am seeing the striping is working. The sandbox works as well. I also tried on m windows machine.  What version browsers do you have? Are you using RDT 6.7.1?

![Screen Shot 2020-04-16 at 7 03 20 AM](https://user-images.githubusercontent.com/1385932/79449017-727d3000-7fb0-11ea-8094-bcab257f1994.png)

**Comment by ospfranco** [comment]
Aha, there might be a misunderstanding, I thought striped meant background color striping, not only in between rows stripes... my bad, closing this issue then
