### ISSUE TITLE
[SSR Error] Warning: Props `id` did not match. Server: "..." Client: "..."

### ISSUE THREAD

**Issue by smilee** [jbetancur/react-data-table-component#596]
## Issue Check list
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README
- [x] You are using React 16.8.0+
- [x] You installed `styled-components`
- [x] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
`Warning: Prop 'id' did not match. Server: "cell-NWxEsEdSh-undefined" Client: "cell-C7y4bqrW4-undefined"`

## To Reproduce
1. Go to any page with an RDT table
2. Open developer tools > console

## Expected behavior
I expected no error messages in the console. I assume it has to do with SSR with Next.js

## Code Sandbox, Screenshots, or Relevant Code
Please include a codesandbox to help **expedite** troublshooting.

https://codesandbox.io/embed/react-data-table-sandbox-ccyuu

Otherwise, add screenshots and/or complete sample code to help explain your problem.
![Error](https://user-images.githubusercontent.com/5793796/83722386-d8646a80-a677-11ea-94f3-2e866cfbdef9.png)

## Versions (please complete the following information)
 - React: 16.10.1
 - Styled Components: Yes
 - OS: macOS Mojave Version 10.14.6
 - Browser: Chrome

## Additional context
 - Using Next.js 9.1.1

**Comment by medv** [comment]
Can confirm this occurs with `next@9.4.4`

**Comment by jbetancur** [comment]
What does your data look like? That error looks like RDT does not have a unique `keyField` defined.

https://github.com/jbetancur/react-data-table-component#basic

Basically, `data` needs some sort of id field that is unique. By default, RDT looks for `id` as the field and then passes that to the components and any `key` props. However, if this key is named something else in your data else you need to use the `keyField` to specify it.

**Comment by smilee** [comment]
I tried everything you mentioned but now I get a different error message: `index.js:1 Warning: Prop `id` did not match. Server: "cell-p__5et8SV-1" Client: "cell-L6Zf7hAzL-1"`

**Comment by jbetancur** [comment]
I'm not sure that RDT is causing that - may be a Nextjs thing with how it is rendering. TO be honest I have never tested in Nextjs,

I did find this issue that may be interesting:
https://github.com/vercel/next.js/issues/12863

**Comment by erikt9** [comment]
The issue comes from `decorateColumns` in `util.js`.  Line 68 calls `id: shortid.generate()` which will generate a unique id which will be different between the server and client side renderings.  My solution was to include an id property with my column objects which will overwrite the autogenerated one (i.e., line 69 calls `...column` which will overwrite the previous set id if an id property is present).

**Comment by jbetancur** [comment]
Nice catch @erikt9! This should probably be something added to the README to specify an column.id when using ssr

**Comment by jbetancur** [comment]
Fixed in README and also added a typing for `column.id`

**Comment by wehnertb** [comment]
I'm using Next.js 9.5.3 - and this issue seems to have reared it's ugly head again.

My info:

  const columns = [
    { name: 'Name', selector: 'find_name', sortable: true,},
    { name: 'Email', selector: 'find_email', sortable: true,},
    { name: 'Phone', selector: 'find_phone', sortable: true,},
    { name: 'Address', selector: 'find_city', sortable: true,},
  ]
  let data = [
                { id: 17788996, find_name: "Wehnert, Bill", find_email: "wehnertb@gotasec.com", find_phone: "", find_city: "<br/>, ", }
             ]

          <DataTable
            columns={columns}
            data={data}
            title="Names"
            defaultSortableField="Name"
            pagination
            keyField='id'
          />
        </div>
  

Yet, I continue to get this: Warning: Prop `id` did not match. Server: "cell-JjFtB2nY_-17788996" Client: "cell-gAHwwspuP-17788996

I am specifying my keyField and I have "id" as a field in my data.  But no matter what I do, it throws this error.
I tried removing the keyField definition from the <DataTable> as my unique field is "id", but that hasn't helped either.

Any suggestions would be greatly appreciated.  I love this component and everything I'm doing is in Next.js - I can't switch out at this time.

Thanks.
