### ISSUE TITLE
Table does not re-render when data changes

### ISSUE THREAD

**Issue by clytras** [jbetancur/react-data-table-component#597]
## Issue Check list
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README
- [x] You are using React 16.8.0+
- [x] You installed `styled-components`
- [x] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
When updating and re-creating the data array with the length of the rows/items remain the same, data table **does not re-render**. If a new item added or an item deleted from the array, the table **does get re-render**.

## To Reproduce
1. Go to https://codesandbox.io/s/react-data-table-component-no-update-zmnbg
There is a timer on mount that changes the first item of the data array title and re-creates the array on setting the state every second
2. No re-render/update happens, but if we click on the second page and back on the first page, we'll see one update

## Expected behavior
The table should be re-rendering when the data array reference changes each second (when re-creating the array with new data and updating the state)

## Code Sandbox
https://codesandbox.io/s/react-data-table-component-no-update-zmnbg

## Relevant Code
```javascript
const data = [
  {
    title: "Conan the Barbarian",
    baseTitle: "Conan the Barbarian",
    year: "1982"
  },
  {
    title: "Terminator",
    baseTitle: "Terminator",
    year: "1984"
  },
  ...
];

function MyComponent() {
  const [myData, setMyData] = useState(data);

  useEffect(() => {
    const timer = setInterval(() => {
      setMyData(prev => {
        const { baseTitle } = prev[0];
        prev[0].title = `${baseTitle} ${new Date()}`;

        console.log("New title for row[0]", prev[0].title);

        // We set a NEW updated data array, but the table never re-renders
        return [...prev];
      });
    }, 1000);

    return () => {
      clearInterval(timer);
    };
  }, []);

  return (
    <DataTable
      title="Arnold Movies"
      columns={columns}
      data={myData}
      pagination
    />
  );
}
```

## Versions
 - React: 16.13.1
 - Styled Components: 5.1.1
 - OS: Windows 10, macOS 10.15
 - Browser: chrome, firefox, edge chromium

**Comment by clytras** [comment]
I have tracked down the issue and it's caused by the usage of pure functional components using [`React.memo`](https://reactjs.org/docs/react-api.html#reactmemo) in [`TableCell`](https://github.com/jbetancur/react-data-table-component/blob/master/src/DataTable/TableCell.js#L21) and [`TableRow`](https://github.com/jbetancur/react-data-table-component/blob/master/src/DataTable/TableRow.js#L39). If we remove the `React.memo`, then we'll get the data to properly update. Please check this codesandbox with a fork and fix I've made:

https://codesandbox.io/s/react-data-table-component-updated-rk92h

I'm not sure if this behavior is intentional, so I selected to report this as a *bug*. If it's considered a bug, I can provide a PR with the fix (`React.memo` removal from `TableCell` and `TableRow`). If this is considered as a feature request because it may break things, then I suggest we add a new boolean property flag to define if we want to use pure data components or not with default set to true. It will control the usage of `React.memo`.

**Comment by zmgirao** [comment]
This fork saved my life.

**Comment by jbetancur** [comment]
@clytras The reason for React.memo is performance-related, where we want to prevent every table row/cell has to re-render on any state change. The reason React.memo is not being "triggered"  is because you're not actually changing the `data` object reference.

This is an easy one to get tripped up on by with JS and especially when using React. JavaScript compares objects by reference, not by contents. arrays are objects too). So, if the object contents change and the reference does not then it has not "changed".

If you are looking to mutate an item in an array you have to deep clone it. The spread operator is great but it only performs a shallow clone that will not work in this case to change the reference. There are a myriad of ways to achieve this. 

Here we use the ` JSON.parse(JSON.stringify(myData))` which while being super gross to use does deep clone to illustrates the point:

```js
  useEffect(() => {
    const timer = setInterval(() => {
      // create a new object with a new reference in memory
      const deepClone = JSON.parse(JSON.stringify(myData));
      deepClone[0].title =  `${deepClone[0].baseTitle} ${new Date()}`;

      setMyData(deepClone);
    }, 1000);

    return () => {
      clearInterval(timer);
    };
  }, []);
```

**We can do better....**
A better pattern is an immutable approach for updating an item in an array.

```js
function updateObjectInArray(array, index) {
  return array.map((item, i) => {
    if (i !== index) {
     // if not the item then bail
      return item
    }

    // Return the new item. we updated the object "deeply" and because map returns a new array
    return {
      ...item,
    }
  })
}
```

Then in your useEffect:
```js
  useEffect(() => {
    const timer = setInterval(() => {
      const deepClone = updateObjectInArray(myData, 0);
      deepClone[0].title =  `${deepClone[0].baseTitle} ${new Date()}`;

      setMyData(deepClone);
    }, 1000);

    return () => {
      clearInterval(timer);
    };
  }, []);
```

I attempted to write about this in the Readme as well: https://github.com/jbetancur/react-data-table-component#optimizing-for-performance-and-caveats

Hope this helps!

**Comment by clytras** [comment]
@jbetancur you are totally correct. How can I be so dumb sometimes... Yes, I know what React memo is for and why we use it.

There is no need to use external libraries to deep-clone the data, we can simply use spread operator to clone the whole data array and the row we want to update. We can do something like this:

```javascript
setMyData(prevData => {
  const updatedData = [...prevData ];
  const { baseTitle } = prevData[0];

  updatedData[0] = { ...updatedData[0], title: `${baseTitle} ${new Date()}` };

  return updatedData;
});
```

And of course it will work:

https://codesandbox.io/s/react-data-table-component-proper-update-9zlff

@zmgirao there is absolutely **no need to use that fork**, just read carefully @jbetancur response and create new objects for the rows you want to update.

@jbetancur Thank you for such an amazing library.

**Comment by jbetancur** [comment]
@clytras no worries. Yup! that will work too, but I believe if you deeply nest it will need to be more deeply cloned (ie iterated on).  Super glad this helped you out! I've pinned this for others.

**Comment by Systemcheck** [comment]
Same issue here. The array is complete new or not? 

`const [tdata, setTdata] = React.useState([])

 function updateDbMessage() {
      let entries = [...tdata]
      const found = entries.findIndex(element => element.id === editDbEntry.id);
      entries[found].message = editDbMessage
      setTdata(entries)
    }
return <DataTable data={tdata} ..... />`

**Comment by jeffdc** [comment]
I am struggling to track down an issue that I believe is related to this. I want to have an editable table. Add, delete, and edit data in place. I do not want to have an edit button in-line with each row (as per the edit example story), rather when the user clicks on a cell it should turn into an editor so that they can edit the content, then when they exit the cell (`onBlur`) the data should be updated.

I have created a stripped down version of this here: https://codesandbox.io/s/react-data-table-editcells-9d65g

The issue is that the data is never updated when a cell is edited. Due, I think, to the columns array being memoized (or otherwise not updated). The custom edit cell needs to invoke an `updateMovie` event on the main table component when it blurs. The `updateMovie` function closed over the original value of the data array when `columns` was first created so that after every edit the table reverts to its original render state which leads me to believe that columns is not updated on a table re-render.

I have been struggling with this for quite some time now and I am sure there is some obvious solution but I am stuck. Any help would be greatly appreciated.

**Comment by jeffdc** [comment]
Oh my. I just saw some changes that went in to RC5 (I was on RC4) that seems to have fixed this. The memoization of the `columns` in the `useColumns` hook was removed. 

I created a somewhat more flexible version of the previously mentioned code sandbox that pulls all of the edit logic into a new `EditableDataTable` component that wraps a `DataTable`. Hopefully it will help someone. https://codesandbox.io/s/react-data-table-editcells-forked-2766t
