### ISSUE TITLE
[FEATURE]: Distinguish "onChangePage" calls

### ISSUE THREAD

**Issue by anjeylink** [jbetancur/react-data-table-component#609]
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README to ensure the feature is not already present
- [x] You read [Creating Issues, Features and Pull Requests](https://github.com/jbetancur/react-data-table-component/issues/387)
- [x] Considered the value versus complexity for all users of the library as well as library maintenance
- [x] Considered if this can be a storybook or documentation example

## It's impossible to know what triggers `onChangePage`.

When user is on any other page than first and clicks on sorting column, RDT triggers `onChangePage` (reset the page to default page) first and after that calls `onSort`.
This cause double data load from server if using `paginationServer` and `sortServer`.

There is another issue with filtering. If user is not on a first page and new data was set from server based on some search input - `onChangePage` is called again.

## Possible solution

Call `onChangePage` only if page was changed using pagination or pass third argument that will help to distinguish events.

**Comment by Angelk90** [comment]
Hi @anjeylink , @jbetancur :

I think it's probably my own problem.

I created an example, link: https://codesandbox.io/s/react-data-table-sandbox-gzfiv?file=/src/index.js

Steps:
1) Click on the page following the first
2) Sort the items by id

When sorted by id, it happens that it is called first
handlePageChange and subsequently handleOnSort.

The problem besides double calling is that I should be on page two with sorting by id asc.
The problem is that according to the pagination I am on page one, this is wrong.

**Comment by jbetancur** [comment]
Yea this has been a bit problematic for some time and is evidenced here:

https://github.com/jbetancur/react-data-table-component/blob/b9e6b888beb5c49b7655f7c6e637fb3ea858a327/src/DataTable/DataTable.js#L150

 What probably needs to happen is it should either only be called when a user changes the page rather than when RDT decides to, introduce a new prop `onChangedPage` for this and fix `onChangePage`, or as @anjeylink suggests add a third param to indicate whether the change was internal or external.

I'd actually like to overhaul how the on<Somthing> callbacks are handled and I think I wrote things this way to avoid prop drilling or passing "too much" through context. I think it would be less problematic to have them just trigger from the source.  For example `onChangePage` could just call be called from https://github.com/jbetancur/react-data-table-component/blob/b9e6b888beb5c49b7655f7c6e637fb3ea858a327/src/DataTable/DataTable.js#L138 and this avoids it being trigged outside of a user clicking on the pagination buttons.

I'd like to get this fixed but I simply have not had the time to test all scenarios Pr's are welcome.

**Comment by Angelk90** [comment]
@jbetancur  : For the proposed solution to use handleChangePage, you could not create a beta test version so we(@anjeylink) test It.

**Comment by romanws** [comment]
Hi. I'm having the same problem - double fetching.

Any chances this feature request could be refloated? 🙏

**Comment by Cauen** [comment]
> Hi. I'm having the same problem - double fetching.
> 
> Any chances this feature request could be refloated? 🙏 Or is there any quick workaround I can do? 😇

My workaround was store **sort timestamp**, and compare with **onChangePage timestamp**
To do this, i'm using **customSort** and **useRef**

```ts
const sortRef = useRef(null)
```

```ts
const customSort = (rows, field, direction) => {
    console.log('CUSTOM SORT')
    sortRef.current = +new Date()

    return rows.sort((rowA, rowB) => {
      // use the selector function to resolve your field names by passing the sort comparitors
      const aField = rowA[field] || ''
      const bField = rowB[field] || ''

      let comparison = 0

      console.log({ aField, bField })
      if (aField > bField) {
        comparison = 1
      } else if (aField < bField) {
        comparison = -1
      }

      return direction === 'desc' ? comparison * -1 : comparison
    })
  }
```

```tsx
<Table
  sortFunction={customSort}
  onChangePage={(pagee, totalRows) => {
    const now = +new Date()
    console.log({ now, current: sortRef.current })
    if (now - sortRef.current < 500) return

    console.log('CHANGE PAGE', { page, pagee, totalRows })
    setData(curr => ({ ...curr, page: pagee }))
  }}
/>
```

**Comment by amabileAJFF** [comment]
Hello, I have the same problem in the most recent version, any solution? because this problem has time and nothing to accommodate it.

**Comment by JRobsonGomes** [comment]
Hello, I'm having the same problem. Is there a solution?

**Comment by Yura0427** [comment]
is it possible to disable page reset by 1 before sorting?
