### ISSUE TITLE
How to set auto reload 10 second for the table 

### ISSUE THREAD

**Issue by inihaekal** [jbetancur/react-data-table-component#638]
Hi John, Thanks for your awesome script.

i had a question,
How to set auto reload the table  from api? 
may you give me the example for this case ? 

if you dont mind, may you give me the sample to put reload/refresh button for the table as well ?

i follow this:
https://codesandbox.io/s/bfdn7?file=/src/index.js

Thanks

**Comment by jbetancur** [comment]
Hi @inihaekal thank you. So that is not an RDT specific question but rather React/JS. I "think" what you are asking about is short polling API data at an interval. 

You'll need to use `setInterval ` to do this and the implementation depends on whether your component is class based or hook based. Here is a pattern that I use extensively in the wild with React hooks.

https://overreacted.io/making-setinterval-declarative-with-react-hooks/

Hope that helps!

**Comment by inihaekal** [comment]
Thank you fir yiur help sir, but im so sorry i still didnt get u .

do you have any example react-data-table-component using axios ?

**Comment by jbetancur** [comment]
@inihaekal I think that is more of a React question than of this library.  I have no idea what your use case is. If you are using React hooks this article is a good place to start:

https://www.robinwieruch.de/react-hooks-fetch-data

You can also take a look at
https://jbetancur.github.io/react-data-table-component/?path=/story/pagination--server-side-using-hooks
and 
https://jbetancur.github.io/react-data-table-component/?path=/story/pagination--server-side
if you are using components
