### ISSUE TITLE
ClearSelectedRows does not seem to be doing anything?

### ISSUE THREAD

**Issue by smammadov1994** [jbetancur/react-data-table-component#723]
I am adding the property "clearSelectedRows" and setting it to true. When I delete a row my useEffect fetches the data and brings it back but it keeps the previous expanded row (which is deleted now) expanded for the next row underneath. I want to make it so that it clears the expanded rows on submit. Is this what this property is supposed to do? and is it just buggy or am I not using it right?

**Comment by jbetancur** [comment]
Due to the the way rdt currently works you need to "toggle" clearSelectedRows so rdt knows to re-render.

Here is an example, albeit with class components.

https://jbetancur.github.io/react-data-table-component/?path=/story/material-ui--override-default-components

**Comment by smammadov1994** [comment]
@jbetancur  how do you even incorporate this? where is this differenceby function coming from? It is so confusing to try anything from storybook dude, can you explain it more?

**Comment by smammadov1994** [comment]
@jbetancur  How are the rows closing after you delete it?

**Comment by jbetancur** [comment]
I'm not sure I understand your question.

Can you provide an example and steps to reproduce so we are clear on what the issue is? A working codesandbox would be even more helpful with the example you are referring to. Here is a code sandbox link you can fork and show what you are referring to:

https://codesandbox.io/embed/react-data-table-sandbox-ccyuu

Also, I noticed you have opened several other issues here with little details. I am eager to help you and so are other contributors, but please make sure that when you log a new issue that you [follow the process for opening new issues](https://github.com/jbetancur/react-data-table-component/issues/387) and also use the issue template so we can better help.
