### ISSUE TITLE
Expandable row doesn't fix to its parent

### ISSUE THREAD

**Issue by quicksilver32** [jbetancur/react-data-table-component#728]
I have table
![image](https://user-images.githubusercontent.com/45488195/101033358-37555e80-358b-11eb-814c-1233e4d76943.png)
As expandable component i use another table
![image](https://user-images.githubusercontent.com/45488195/101033983-610e8580-358b-11eb-9106-d429b27306f8.png)
But when i sort main table, expandable component stays under first row
![image](https://user-images.githubusercontent.com/45488195/101034422-89967f80-358b-11eb-9053-200f22fef682.png)
In example there's no such bug. How to fix it?

**Comment by jbetancur** [comment]
Does your data have a unique identifier? For examplle `[{id: 1}, {id: 2}]`

By default RDT uses `id` but if your data key field is different you will need to specify a keyField prop on the Table, otherwise, RDT will have trouble with expanders.

See `keyField` here:
https://github.com/jbetancur/react-data-table-component#datatable-properties

**Comment by quicksilver32** [comment]
@jbetancur I think it has 
![image](https://user-images.githubusercontent.com/45488195/101044892-ed6f7700-3590-11eb-95d7-b2c49afc6f14.png)

**Comment by quicksilver32** [comment]
@jbetancur oh thanks! I added "id" to my data and it works, thank you!
