### ISSUE TITLE
Column sortFunction only works fine in one direction

### ISSUE THREAD

**Issue by KostasKoufos** [jbetancur/react-data-table-component#750]
## Issue Check list
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README
- [x] You are using React 16.8.0+
- [x] You installed `styled-components`
- [x] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
When adding a custom sortFunction for a column, it only works fine in one of the sort directions.

I first encounter the bug when I had a column with an integer value represented in string type. I created a custom sortFunction to parseInt the string and then compare it. But it also happens if you have an integer value column and you add a custom sortFunctoin doing a simple  a.columnValue >= b.columnValue

## To Reproduce
I added a codesandbox example with three columns:
- Column with number in string type and a custom sort function
- Column with number in int type and a custom sort function
- Column with number in int type. 

For the custom sorted functions, the first time we click on the headers (desc direction) the columns are not sorted as they should. If we sort for ASC direction then they are sorted fine.

## Expected behavior
The sorting should work fine every time we click on the header to sort, neverminding the sortDirection.

## Code Sandbox, Screenshots, or Relevant Code
https://codesandbox.io/s/rdt-bug-customsort-vl1xs?file=/src/App.js

## Versions (please complete the following information)
 - React (RDT requires 16.8.0+)
 - Styled Components
 - OS: Windows
 - Browser: Chrome

**Comment by pangeacode** [comment]
in code example implementation of sortFunction is not correct
![image](https://user-images.githubusercontent.com/66420034/174796289-a04bc7b3-1e38-4348-afe7-92d8d94c8b74.png)
sortFunction should return number: ==  result:0 , >: (result> 0), <: (result < 0)
you should use 
`sortFunction: (a, b) => {
      return a.YearInt - b.YearInt;
    }`
instead of
sortFunction: (a, b) => {
      return a.YearIntCustom >= b.YearIntCustom;
    }
    
 default sort could be:
`const defaultGridColumnSortFunction = (row1: any, row2: any, valueAccessor: (row: any) => any): number => {
  let value1 = valueAccessor(row1)
  let value2 = valueAccessor(row2)
  if (value1 === value2)
    return 0

  return value1 > value2 ? 1 : -1
}`
...
`sortFunction: (a, b) => defaultGridColumnSortFunction(a,b,row => parseInt(row.year, 10))`
