### ISSUE TITLE
Is no one else getting this error? *Could not resolve dependency React >= 16.8.0*

### ISSUE THREAD

**Issue by LuisDev99** [jbetancur/react-data-table-component#784]
I'm using React v17.0.1. 

When I enter: 

```npm
npm install react-data-table-component styled-components
```

I get this error:

![image](https://user-images.githubusercontent.com/30758539/108733939-8bba0b80-74f4-11eb-8b41-34ae85de598a.png)

I saw someone that got it running somehow with React v17, but I don't know how. Should I just do this:

![image](https://user-images.githubusercontent.com/30758539/108734119-c0c65e00-74f4-11eb-9ac0-d47e3a3189eb.png)

?

I tried doing this (just in case):

```npm
npm install react-data-table-component@latest styled-components
```

But no luck

**Comment by jbetancur** [comment]
Srange that I am not able to dupe the issue, but looking at the `peerDependencies` they don't look right.


I just updated RDT to alpha-8 and a new stable 6.11.7 and fixed the peerDepenencies to properly support React 17, however, I just realized that people are getting the alpha versions by default as `@latest` which is incorrect.

I would reinstall RDT at version 6.11.7 which should help fix your issue, but, otherwise feel free to use alpha version 8 as well,

**Comment by jbetancur** [comment]
until I fix pre-releases as latest tags try this

npm install react-data-table-component@6.11.7 styled-components

or if you prefer to use the alpha version

npm install react-data-table-component@7.0.0-alpha-8  styled-components

**Comment by LuisDev99** [comment]
@jbetancur Thanks!

Tried: 

```npm
npm install react-data-table-component@latest styled-components
```

It works now! Just for FYI, this is the version that it installed:

![image](https://user-images.githubusercontent.com/30758539/108910194-239a2100-75eb-11eb-9c21-80c426fee301.png)

Cheers!
