### ISSUE TITLE
Efficiently update a single column............?

### ISSUE THREAD

**Issue by slimandslam** [jbetancur/react-data-table-component#816]
## Efficiently update a single column?
More of a general question than a bug. If I'm displaying a table for the user, and I want to
update one column of the table, is there an efficient way to do that?
The column contains a "status" string like "PROCESSING", "BUILDING", "ERROR", or "READY"
I have an API call that returns just an array of status strings for that table column. 
I'd like to update just that one column (possibly repeatedly) without re-rendering everything else.
The user will click an "update" button that will do an API call and return the array of status strings.

**Comment by jbetancur** [comment]
If the `data` props passed to `DataTable` changes it will re-render because that how React works, in that you pass a prop, and the prop changes then there is a re-render. However, RDT has several optimizations using memoization to reduce all the many calculations performed when such a re-render occurs, particularly on the main `DataTable` component as well as each `TableCell`. 

But there is a cost to this memoization (caching) and it really depends on how complex the cell is. I.E. Does the "do not re-render" logic perform better than just re-rending it anyway?  I've tried to design things to be as performant as possible to a general audience, but there are always edge cases.

Anyway, the best way to test your app and RDT with chrome performance tools/flame graphs. There are tons of articles out there on how to do this.

Are you experiencing some performance issues that you need to optimize?

I would also make sure you're memoizing or when passing non-primitive props that they are not generating a new reference:
https://github.com/jbetancur/react-data-table-component#optimizing-for-performance-and-caveats
