### ISSUE TITLE
SelectableRows  when using Pagination Server Side 

### ISSUE THREAD

**Issue by mary118** [jbetancur/react-data-table-component#875]
Hello, I have a problem which boils down to the fact when I add the server side pagination I cannot select all the rows of the table except the visible rows of the current page and when I scroll to the next page I lose the elements already selected

**Comment by jbetancur** [comment]
Server side pagination by design only displays the rows that you have requested from the server. If you query for 10 out of 20  rows you can only select 10 rows and the other 10 rows are requested on a subsequent page change. There is no way to know before hand what rows select in this case. You might as well use client side pagination and load all of your data if you need to select all rows, but this depends on how much data you expect the browser to handle for you and the max records your API supports at a time.

**Comment by mary118** [comment]
thank you for your help, I noticed that after multiple tests, the only solution I opted for is to be able to keep the values ​​selected in the previous pages each time.
Regards

**Comment by keshavsharma07** [comment]
onSelectedRowsChange gets called everytime, when i click on next page button. How to stop it

**Comment by balpreetbrar** [comment]
> onSelectedRowsChange gets called everytime, when i click on next page button. How to stop it

I am also  facing the same issue.
