### ISSUE TITLE
Column Filtering: filter by columns

### ISSUE THREAD

**Issue by mstruensee** [jbetancur/react-data-table-component#899]
will this feature be merged?
https://www.npmjs.com/package/react-data-table-component-with-filter

**Comment by jbetancur** [comment]
I was not aware this existed.  What I would like to see is some design into what column filtering should be. I have currently been focused on version 7 of RDT and other features

**Comment by mstruensee** [comment]
I agree, I already was checking out the code changed and it didn't allow for much customization ... maybe I'll check on his version, add he said he was going to do a PR ... which I don't see ... 

how soon for v7?

**Comment by jbetancur** [comment]
V7 was released a couple days ago. make sure you check out the release notes as there are a number of significant changes.

**Comment by mstruensee** [comment]
nice! looks like I will spend my day updating to v7 :D

**Comment by mstruensee** [comment]
easy upgrade! thanks!

so what timeline you looking at for this column filter feature? I could try and tackle porting his into v7 but I am no bueno at TS :D

**Comment by jbetancur** [comment]
No eta at this time as I have been quite busy, but it would be good to start with a visual design of what filtering should look like. Ive seen inline inputs in columns and there's also ... menu per column filtering. The caveat to this feature is if you have column filtering one way others will want it another way and want to over customize it. The goal here would be to find a happy medium with functionality and good UX. Another thing to consider is allowing someone to inject their own text inputs.

**Comment by davebrown1975** [comment]
As an interim workaround can we have the ability to put our own controls into the column header without clicking affecting the sorting?

**Comment by mstruensee** [comment]
I was thinking the same thing, maybe I will be brave enough to even open a PR :P

**Comment by davebrown1975** [comment]
Hi, has there been any further consideration against this request?   No pressure intended but I do need to make a design decision as to whether I can continue using this component,  without column filtering however this would be a blocker,  which is a shame as I really like this component otherwise.

**Comment by jbetancur** [comment]
@davebrown1975 The next feature priority is on filtering columns and I am already working on a design. It's the number 1 feature request and it will be the next minor version 7.4.0. The challenge is making it customizable "enough", intuitive enough and performant. I appreciate that you are using this library and that you have some time constraints, but currently being the only main contributor to this project dropping features on a dime is not easily achievable.  I can't give a time frame other than I am working on it now.

Also, I develop this library in my free time because I love open source and giving back. It's free for everyone to use as is. I receive no income for it and while I don't have an expectation that anyone chip in via open collective, if they do, it does allow me to focus more on the project to keep delivering new features.

**Comment by jendamozna** [comment]
Hello, whats the status on this?

**Comment by jean-maxime** [comment]
Is there any news for this feature ?

**Comment by rRakarare** [comment]
I dont want to be annoying but can someone give us info about the progress of this feature? I would love to know. With this feature implemented i think this library will be realy awesome as an easy to use react-data-table lib.

**Comment by prokie** [comment]
Would also like to know if there is any progress in this feature.

**Comment by thiagodsti** [comment]
I would also like to know if there is any progress in this feature

**Comment by lucajung** [comment]
@jbetancur Any news on this feature? You closed it, does that mean an implementation is still being implemented or is the feature not being pursued?

**Comment by ADTC** [comment]
@jbetancur I'm also looking for the feature. We need it as a requirement in our project. Without being able to utilize the feature, we may have to move to another table-building library unfortunately.
