### ISSUE TITLE
Relative positioned components within a data-table row are cut off by the `overflow-y: hidden` on the ResponsiveWrapper

### ISSUE THREAD

**Issue by anmcn** [jbetancur/react-data-table-component#965]
## Issue Check list
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README
- [x] You are using React 16.8.0+
- [x] You installed `styled-components`
- [ ] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
Relative positioned components within the react-data-table, such as Dropdown menus, are cut off by the `overflow-y: hidden` on the ResponsiveWrapper

## To Reproduce
Create a data-table containing rows containing a component such as a drop-down menu. When the menu is opened near the upper or lower limits of the table, the menu will be truncated. 

## Expected behavior
To see relative position components rendered in full.

## Code Sandbox, Screenshots, or Relevant Code
What we get...
![image](https://user-images.githubusercontent.com/2274417/141422185-89f4fc3b-8874-4a21-a866-2413f7a0efd0.png)

What we would like to get...
![image](https://user-images.githubusercontent.com/2274417/141422342-5370a4af-b251-408a-9415-3a5ecc7b718e.png)

## Versions (please complete the following information)
 - RDT - 7.0.2
 - React - 17.0.2
 - Styled Components - 5.3.1
 - Browser - chrome (95.0.4638.54). Problem also exhibits with safari & firefox

**Comment by KelvinTegelaar** [comment]
Also 'suffering' from this, and looking for a quick fix :)

**Comment by jbetancur** [comment]
This issue has been raised before but is really hard to solve because of the way overflow y/x works. http://www.brunildo.org/test/Overflowxy2.html

In other words to allow overflow-x visible is not possible. removing the overflow causes the table to not be responsive as designed or causes a y scroll bar which is undesirable

It looks like you are using bootstrap, but the modern implementation for these types of controls that is recommended should be using smart or dynamic positioning via javaScript.  As an example material ui this concept which means the popovers are not affected by the overflow-xy idiosyncrasies

I'm not sure how to fix this as I have tried every hack imaginable. There used to be a feature (which I removed since almost no one used it) that would allow you to pad the bottom of the table, but it was ugly at best. e.g `style="padding-bottom: 250px; margin-bottom: -250px;`

A possible solution if you are already set on bootstrap would be for RDT to expose a style that you can override via `customStyles` prop where you could perform your own padding as described above.

Open to solutions that do not break responsive x-scrolling

**Comment by anmcn** [comment]
Why does the y-overflow need to be set to hidden? I forced the overflow to visible in our application, and I'm not seeing anything untoward so far.

**Comment by Ercules76** [comment]
@anmcn 
in wich element you set overflow-y: visible?

**Comment by anmcn** [comment]
This is what makes a work-around so difficult - there is a hidden parent <div> with `overflow-y: hidden` specified as an explicit style (ResponsiveWrapper.tsx). I ended up wrapping the table with a component with a className that selects the subordinate <div> and overrides the `overflow-y: hidden`:
```
.ovfix div {
  overflow: visible!important;
}
```
