### ISSUE TITLE
Error: Invalid hook call. Hooks can only be called inside of the body of a function component.

### ISSUE THREAD

**Issue by ajithv11** [jbetancur/react-data-table-component#990]
I got the following error after upgrading my nodejs version and performing npm intall to make the changes

Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

This is causing from  react-data-table-component ie when I remove Datatable this warniong disappears and page get loaded

**Comment by Daan-Reede** [comment]
Same here

**Comment by PleatherStarfish** [comment]
I'm experiencing this issue as well. I replicated the expanding rows basic example exactly. The table renders, but the expanding rows don't work, and I get this "Invalid hook call" error.

**Comment by phlerp** [comment]
I have checked that I have not several versions of React, and I have also checked that the versions are not mismatching (would have been strange if they were as the rest of my system works fine). So the obvious conclusion would be that something is up with how hooks are used in the data table component.

One thought, I am using class component but I assume the data table component is a functional component since it uses hooks. Could that be a reason for the problem I'm having?
